### ISSUE TITLE
Pokročilá validace odpovědí

### ISSUE THREAD

**Issue by pesikj** [Hedwika/Czechitas-Data-Games#37]
Odstranění zbytečných mezer
Zaokrouhlování
Case insensitive porovnání
Ignorace abecedního pořadí v případě záznamů

Zřejmě bude potřeba přidat číselník "typ odpovědi" k úkolu.

**Comment by Hedwika** [comment]
Odstranění zbytečných mezer:
    answer = answer.join(answer.split())

Zaokrouhlování:
    def round_half_up(n, decimals=0):
        multiplier = 10 ** decimals
        return math.floor(n * multiplier + 0.5) / multiplier
    answer = round_half_up(answer, 2)

Case insensitive porovnání:
    answer = answer.lower()

Ignorace abecedního pořadí v případě záznamů:


Zřejmě bude potřeba přidat číselník "typ odpovědi" k úkolu:

**Comment by Hedwika** [comment]
Myslím, že hotovo :) @pesikj
