### ISSUE TITLE
Vytvořit Wiki stránku s úkoly a řešeními úkolů z uplynulých událostí

### ISSUE THREAD

**Issue by pesikj** [Hedwika/Czechitas-Data-Games#43]
Stránka by měla obsahovat zadání úkolů, vstupní data a případné další komentáře

**Comment by Hedwika** [comment]
Struktura:
a) Pokud je event end < today, vypiš úkoly z tohoto eventu. Pokračuj na konec všech eventů.
b) Vypiš eventy, jejichž event end < today. Proklik přes každý event na stránku, kde jsou vypsány úkoly z něj.

Potřebuji, aby view čerpal jak z modelu Event, tak z modelu Assignment. Jak na to?
Jak mohu otestovat?
Jaký je veřejný web?
